<script type="text/javascript">

$(document).ready(function(){
	$("#s1").click(function(){
		$("#textholder").html('<div id="manicon"><h3 id="textmargin" style="float: left; padding-top: 30px;">Project Design, Management & Consultation</h3></div>	  <p id="manlisttext">The most critical phase of any project is planning. Ensuring you have the proper foundation is critical to the success of your project. Our Business Services, Inc. can assist you in the planning of your project, procurement of hardware and software as well as implementing your project. Whether you need to augment your in-house staff with additional labor to compete a project on budget or outsource the entire project, our business can help. Some projects that we specialize in are:</p><ul id="manlisttext" style="float: left; padding-left: 20px;"><li>Server Installations and Migrations</li><li>Server Virtualization and VDI</li><li>Storage Solutions: ISCI; SAN & DAS</li><li>Networking: LAN, WAN. Firewalls, Loading Balancing, Wireless Networking</li><li>Data Retrieval</li><li>Network Configuration and Repair</li><li>Software Installation</li><li>Troubleshooting and Support</li> <li>High Availability Clustering</li> <li>Remote Access Solutions</li><li>PC Roll Outs</li> </ul>');
	});
	$("#s2").click(function(){
		$("#textholder").html('<div id="manicon"><h3 id="textmargin" style="padding-top: 30px;">Help Desk Services</h3></div><p id="manlisttext">Our Helpdesk is available to your users via email, telephone or through desktop sharing sessions. Our helpdesk is 100% USA based and knowledgeable in a vast array of equipment and software. If your issue can\'t be solved remotely, we will send a technician to your office to resolve the problem.</p><p id="manlisttext">Managed Services clients can schedule weekly, bi-weekly or monthly visits for peace of mind. Your users will receive one-on-one service and your budget won\'t be burdened with high costs of an in-house IT person.</p><ul id="manlisttext" style="float: left; padding-left: 20px;"><li>On-site Technician with regularly scheduled visits</li><li>USA based phone, email and remote desktop support</li></ul>');
	});
	$("#s3").click(function(){
		$("#textholder").html('<div id="manicon"><h3 id="textmargin" style="padding-top: 30px;">Security</h3></div><p id="manlisttext">Our team understands what it takes to keep your system safe, secure and private. With high levels of technical expertise, we can assist in a wide range of security. From firewalls, VPNs, routers and switches we can keep your information safe. Our business utilizes best practices and current industry knowledge to keep your system covered.</p><ul id="manlisttext" style="float: left; padding-left: 20px;"><li>Network Security</li><li>Physical Security</li><li>CCTV & IP Camera Systems</li></ul>');
	});
	$("#s4").click(function(){
		$("#textholder").html('<div id="manicon"><h3 id="textmargin" style="padding-top: 30px;">Spam & Malware Protection</h3></div><p id="manlisttext">Your email is a vital part of your business. Sometimes it can be vulnerable to attacks from spam, viruses, phishing, and malware. With email & spam protection from our business, your company will be safe and you can relax knowing your email is safe.</p><ul id="manlisttext" style="float: left; padding-left: 20px;"><li>Email Protection Service</li><ul style="padding-left: 15px;"><li>Spam & Virus Filtering</li><li>Email Archiving</li></ul><li>Gateway AntiVirus at the network level</li><li>Managed AntiVirus on all corporate devices</li><li>Virus and Spyware Removal</li></ul>');
	});
	$("#s5").click(function(){
		$("#textholder").html('  <div id="manicon"><h3 id="textmargin" style="padding-top: 30px;">Break Fix Services</h3></div><p id="manlisttext">Our business has a wide range of IT knowledge, if you break it, we fix it. Utilizing diagnostic tools for troubleshooting and years of experience, your equipment will be restored to peak performance. Many issues can be repaired at your office and those more challenging problems can be repaired at our lab. </p><p id="manlisttext">We offer a loaner service so that you may continue to work while we are repairing your equipment.</p><ul id="manlisttext" style="float: left; padding-left: 20px;"><li>PCs, Laptops & Mobil Devices</li><li>Printers</li><li>Router and Switches</li></ul>');
	});
	$("#s6").click(function(){
		$("#textholder").html('<div id="manicon"><h3 id="textmargin" style="padding-top: 30px;">Backup, Disaster Recovery & Data Recovery</h3></div> <p id="manlisttext">Our business has solutions for backing up, restoring and getting back to business after a setback. Fires, break-ins, storms and other unfortunate things can take your system down, but if you plan for a disaster before it happens, you will have peace of mind in knowing that your system will be safe and the situation is curable.</p><ul id="manlisttext" style="float: left; padding-left: 20px;"><li>On-site and Off-site Backups</li><li>Co-location Services and other Disaster Recovery options</li><li>Data Recovery from crashed, infected, and damaged hard drives and arrays</li></ul>');
	});
	$("#s7").click(function(){
		$("#textholder").html('  <div id="manicon"><h3 id="textmargin" style="padding-top: 30px;">Network Health Monitoring</h3></div><p id="manlisttext">Our monitoring solutions will scrutinize all connected devices and watch for network failures of any kind. Alerts will also be in place to inform us about changes, high utilizations or any potential interrupts. We also provide custom reports to summarize how your network is doing.</p><ul id="manlisttext" style="float: left; padding-left: 20px;"><li>Monitoring of all network attached devices</li><li>Alerting of any potential issues on the network</li><li>Reports showing network statistics, uptime and health</li></ul>');
	});
		$("#s8").click(function(){
		$("#textholder").html('  <div id="manicon"><h3 id="textmargin" style="padding-top: 30px;">Paperless Office</h3></div><p id="manlisttext">Our business can assist you in your decision to go paperless. We can design a document scanning solution with custom secure document storage and retention for your business. Of course easily finding those documents is just as important as digitizing them so we have multiple user friendly solutions for document retrieval.</p><p id="manlisttext">If you want Document Management managed by us, you are in luck. Our professionals will meticulously scan each and every one of your documents so they can be stored on a digital media. Once your documents are archive we will stop by periodically on a schedule of your choosing to add any new documents to the digital archive.</p><ul id="manlisttext" style="float: left; padding-left: 20px;"><li>Document Scanning</li><li>Digital Archiving</li><li>Document Retrieval</li></ul>');
	});	
});

</script>